[workspace]
members = ["contracts/*"]

[profile.release.package.name-service]
codegen-units = 1
incremental = false

[profile.release]
rpath = false
lto = true
opt-level = 'z'
overflow-checks = true
debug = false
debug-assertions = false